### ISSUE TITLE
Improve integration of supported items

### ISSUE THREAD

**Issue by Philippe-Choquette** [CatimaLoyalty/Android#1003]
The description of the app on the Google Play Store states the following:
_For your barcodes, memberships, loyalty programs, coupons and tickets._

Although many item types are claimed to be supported (which is true in practice), the app doesn't really seem thought out for them:
- The title of the app only mentions loyalty cards
- Upon first use, the tutorial indicates that the + button is to add a card. A ticket or coupon isn't one.
- The edit screen is named "Edit card" and contains fields like "Card ID" and also "Balance", which is only really relevant in the context of a loyalty card.

The app could be a great hub for storing all savings-related items, but could benefit from picking the type of item when adding one.

**Comment by TheLastProject** [comment]
> The title of the app only mentions loyalty cards

Google limits the length of the app title, so we can't put more there. Seeing how many more loyalty card than coupon or ticket apps there are on Google Play, this is probably what people search for and thus shouldn't be changed.

> Upon first use, the tutorial indicates that the + button is to add a card. A ticket or coupon isn't one.

Given Catima's core design is loyalty cards, that seems fine to me. It could maybe be renamed to Add Entry or something, but given we are at almost 20 thousand users on Google Play and this is the first time anyone mentions this I am hesitent to change anything so basic. "Cards" are an easy to understand concept with real life equivalent, an entry is much more abstract.

 > The edit screen is named "Edit card" and contains fields like "Card ID" and also "Balance", which is only really relevant in the context of a loyalty card.

I am not really seeing any benefit in forcing users to choose a type which then disables some options like balance. It just seems to me like this will confuse more users and will require all types of complex code to migrate things between types if the user accidentally chose the wrong type and realizes they want a balance after all. It is much easier, also to users, to just present the options and allow them to be left empty.

> The app could be a great hub for storing all savings-related items, but could benefit from picking the type of item when adding one.

For reasons stated above I am really not convinced this is an improvement. If anything, it complicates both the codebase and UI for no apparent gain. Even coupons can benefit from setting a balance for a quick view. I often use a balance of 5€ with a note of "For order over 20€" for example.

I want to focus on Catima staying simple instead of 100% supporting every feature ever and think the current setup is flexible enough. So I'm sorry, but I am not interested in these changes and also won't accept a PR adding this due to the increased maintenance burden for little gain.

**Comment by Philippe-Choquette** [comment]
Fair enough, especially for the complexity this adds to the code. Thank you for taking the time to reply to every request and for your awesome work!
