### ISSUE TITLE
Add "valid from" field

### ISSUE THREAD

**Issue by cpy82** [CatimaLoyalty/Android#1032]
Could you maybe add a "Valid from" field to e.g. add a start date to future voucher codes?

Thank you!

**Comment by TheLastProject** [comment]
Needs some deciding on how to display this in the main card list, but seems like a reasonable feature to add.

**Comment by vanogrid** [comment]
Hi @TheLastProject, I would like to work on this task if it's still available.

**Comment by TheLastProject** [comment]
Sure, I've assigned it to you.

I'm not completely sure yet how this should look, but my basic idea would be:
1. In the Edit Card view, under Options, place a "Valid from" above "Expiry date" with the default value being "Any date"
2. In the LoyaltyCardViewActivity's info screen, add an extra line "Valid from: ..." above the "Expires:" line, colouring it red if not yet valid.
3. In MainActivity I'm not sure yet. Right now we have a schedule icon for the expiry but I have no clue what kind of icon we could use for valid from. Hopefully something decent can be found in Android Studio's "Configure Vector Asset" screen. Otherwise we may want to make a copy of the current expiry icon and add a little "play" symbol in the bottom right of it to signify "start"? This might need a designer in the worst case, although I'd prefer to avoid that if people (however, if all the code works and we just need an icon design, I'm willing to mark PR with hacktoberfest-accepted so it won't be blocked by a designer being available or not)
