### ISSUE TITLE
Add one per line view

### ISSUE THREAD

**Issue by m3thm4th** [CatimaLoyalty/Android#1041]
Loyalty Card Keychanin has a nice view of one card per line, add an option to use that same view- This allows for a less busy view.

**Comment by TheLastProject** [comment]
I replaced the old layout Loyalty Card Keychain uses because it didn't really use space very optimally for bigger screens. I'm not planning on bringing it back because I think the new layout is better for most users (including myself) and I'm also not planning on adding an extra option as that means maintaining 2 code paths for the main screen.

So, simply put, I don't think the amount of work adding and maintaining such a view really fits the amount of gain for most users and I only have a limited amount of time in my day. If you prefer the old layout, I would recommend you to instead stay with version 2.9.0, the last version with the old layout. It's available here on Catima GitHub and in F-Droid Archive :)
