### ISSUE TITLE
Allow browsing filesystem for images

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1056]
Currently, Catima only offers the gallery app when choosing a picture to import, not the user's File Browser. While the gallery is the best choice in the vast majority of cases, depending on how the user likes to organize their files the user's File Browser may be easier to use in some cases.

The challenge here is figuring out how to allow this while still ensuring that Android won't let us select any non-image content.

It should be noted that Ghost Commander already offers itself as an option, but LineageOS Files doesn't.

This would affect;
- "Select image from gallery" button in ScanActivity
- Icon image picker in LoyaltyCardEditActivity
- Photo picker in LoyaltyCardEditActivity

(I got this request over email and it makes sense to me, labelling it Good First Issue as I'm quite sure that implementing this is quite standard Android and won't need any Catima-specific knowledge or reading up.)

**Comment by gulammoyuddin** [comment]
I am a beginner can I work on it

**Comment by TheLastProject** [comment]
Sure, assigned it to you. I don't know the answer to this from the top of my head but I'm sure this is so common you'll easily find a lot of random StackOverflow and blog posts :)

**Comment by xenom34** [comment]
I tried to install another file browser, and yet, it does ask me to choose the one I prefer🤔. 
***Testing without changing anything :***
![Screenshot_20221026-225137](https://user-images.githubusercontent.com/45591509/198136828-be4e147e-bef3-4de6-a13e-a69cb4c21aec.png)

But I think it depends very much on how each file browsers are implemented.
Otherwise, this can be also done by using "Intent.ACTION_GET_CONTENT" instead of "Intent.ACTION_PICK" when creating the Intent (and still using mime 'image/*'). In my case, it opens what I believe is the default file browser. However, by opening the menus available in the drawer, there is the option to select a specific explorer.
![Screenshot_20221026-230417](https://user-images.githubusercontent.com/45591509/198138302-07d9b811-14a8-4f24-af8a-265fbcda379e.png)

If you prefer to use Intent.ACTION_GET_CONTENT, I can try to work something out by assigning the issue to me.

**Comment by TheLastProject** [comment]
Looking at [the documentation](https://developer.android.com/reference/android/content/Intent#ACTION_GET_CONTENT) there seem to be a few gotchas like `EXTRA_LOCAL_ONLY`. I think it's worth a try, see how it feels on a variety of devices, see if it is better or worse on most devices.

**Comment by TheLastProject** [comment]
Given we haven't heard from @gulammoyuddin in 24 days and Hacktoberfest is almost over, reassigning feels fair yeah :)

**Comment by TheLastProject** [comment]
Fixed through #1116
