### ISSUE TITLE
Material You accent color

### ISSUE THREAD

**Issue by the4anoni** [CatimaLoyalty/Android#1063]
Add option to get accent color from material you.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Could we have an update on the decision please?

**Comment by TheLastProject** [comment]
See https://github.com/CatimaLoyalty/Android/issues/950#issuecomment-1265383908, it is a bug with Google's libraries that detect Material Colour support.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
> See [#950 (comment)](https://github.com/CatimaLoyalty/Android/issues/950#issuecomment-1265383908), it is a bug with Google's libraries that detect Material Colour support.

With that said, other apps on my phone work with Material You. Could there be a possible fix in the meantime until Google fixes this? I doubt my phone will get Android 13/14.

**Comment by TheLastProject** [comment]
I'm not planning to work on this myself because I think the other issues and feature requests have more priority and I only have so much time and energy left after a full work week. Any change here would need testing also on Samsung and Xiaomi devices (due to their custom UI) which I don't have, which also makes this a lot more difficult. It would be much better if Google would fix this, although I am curious how other developers are working around this Google bug.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
I responded to a similar issue with another app on GitHub just now and their idea was to base the detection on the SDK version of the device. https://github.com/libre-tube/LibreTube/issues/2189#issuecomment-1335887436

**Comment by TheLastProject** [comment]
That doesn't seem like a good idea to me, I don't think there's any guarantee that a device being Android 12L means it has a version of Samsung's OneUI or Xiaomi MUIU that has correct contrast for all Material You colours. While Google's check blocks Material You colours on too many devices, just enabling it everywhere will possibly break stuff for some users. And I find things not breaking more important.

*sigh* It's annoying Google doesn't just solve it and now millions of apps have to all find their own workaround and hope they don't break something while doing so. So much wasted time everywhere :(
