### ISSUE TITLE
Want to update README.md file and adding CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by Sowham-3098** [CatimaLoyalty/Android#1082]
I want to add how to contribute section and also contributors profile into main README.md file and want to add Code of conduct file.

can I do this?

**Comment by TheLastProject** [comment]
Hey there,

I'm not really interested in adding a contributors section to the README because GitHub already puts such a section on each page:

![image](https://user-images.githubusercontent.com/1885159/195423161-eb0e2c67-6e6f-436d-84a3-b88521cecae0.png)

For a Code of Conduct, that is really something I should do myself as it's very important that the Code of Conduct is correct for the community in question, so I don't think having someone else than me add a Code of Conduct is a very good idea.

Thank you for trying to help though :)
