### ISSUE TITLE
Choose image source from Add button without opening camera

### ISSUE THREAD

**Issue by proideo** [CatimaLoyalty/Android#1094]
I think it would be interesting to be able to choose the image source (Camera/Select from gallery) or "Manually enter ID" from the Add button without opening the camera. These options could appear in a submenu of buttons when the Add button is tapped.

**Comment by TheLastProject** [comment]
This feature request makes no sense to me and I won't be accepting pull requests to make this change either.

It's the exact same amount of clicks for gallery/manual (`+` button -> its own button)
It's one click extra for the camera (`+` button -> camera button instead of just `+` button)

I see no advantage to this at all.
