### ISSUE TITLE
 import Not possible 

### ISSUE THREAD

**Issue by Kenarso** [CatimaLoyalty/Android#1148]
Import Not possible

I have created an export on a Samsung Galaxy S20 current software version. Android 12. 
I want to import on a Google Pixel 4a with Android 13, also current software version. 
After selecting the zip file, I can enter the password, but nothing is added. If I repeat the import, either nothing happens or the app crashes. I am no longer asked for a password.

**Comment by TheLastProject** [comment]
"Current software version" isn't really clear enough, as it depends on the app source and on Google Play the roll-out is often partial so what is latest for one user isn't latest for someone else. Is it version 2.21.0 in both cases?

I can't reproduce this issue. I've done the following:
1. Open Catima 2.21.0 on my FP3 (Android 12)
2. Go to Import/Export
3. Click Export
4. Enter the password "testpass"
5. Send the export to my laptop (over Telegram because I'm feeling lazy)
6. Open Android Studio
7. Start an Android 13 emulator
8. Put the file on the Android 13 emulator using the Device File Explorer (in Documents on Internal Storage in this case)
9. Open Catima on Android 13
10. Click Import/Export
11. Click From Filesystem
12. Select file and enter "testpass"
13. Wait for the import to complete

In my case, the import completes correctly and all my cards are there.

Could you please give me step-by-step exactly what you did and how you sent your export from one device to the other and perhaps send me your export file (see possible contact ways on https://sylviavanos.nl/#contact) so I can check if there is maybe something different in your cards that doesn't import correctly?

**Comment by Kenarso** [comment]
I use version 2.21.0 of F-Droid on both smartphones.

I carry out the following steps on Android 12:
1. click on Menu
2. click on Port/Export
3. select Export
4. enter password (15 characters, upper and lower case letters, numbers and special characters)
5. save it on my Nextxloud

Now I open the app on my Android 13 smartphone with the following steps:
1. open menu
2. click on Import/Export
3. click on 'Choose from file system
4. select Zip on Nextxloud
5. enter password and click OK
No maps have been imported. 
If I repeat these steps, either nothing happens or the app crashes.

**Comment by TheLastProject** [comment]
Hmm, I can't really imagine Nextcloud to corrupt an export like that. I also tried to export using the following password to check if special characters might break it but to no avail: `@#£%&-+()/*"':;!?~`|•√π÷×¶∆¥$€¢^°={}\_©®™✓[]`.

Maybe if you install [Scoop](https://f-droid.org/en/packages/taco.scoop/) and [configure it](https://github.com/TacoTheDank/Scoop/wiki) it could tell you why the crash is happening and maybe that'll help me figure it out. Otherwise I don't think I can fix this issue without having your export (my last guess would be some kind of setting on some card/group or some image is causing the import to fail) .

**Comment by Kenarso** [comment]
I have now been able to isolate the problem somewhat.
I use the two special characters "?" and "!" in my password. On the computer I can unpack the zip without problems.
But when I try to open the file with the file manager on the Pixel, I get an error message when I enter the password. I guess that the integrated unpacker can't handle one of the special characters.
After I did the export without PW I could do the import on the Pixel without problems.
Thanks for your awesome app and your help here!

Regards Oliver
