### ISSUE TITLE
Add an upload for files instead of taking a picture

### ISSUE THREAD

**Issue by guy-teube** [CatimaLoyalty/Android#1196]
Hello,
I use Catima every day and it does the job :)
I appreciate the functionality to take a photo of a document, to keep a trace of the real file with the barcode.
But a photo can be a large file, and sometimes not really readable (my phone is old and take bad quality photos).
I wonder if it would be possible to add a functionality to upload real files, like a pdf or jpg files.
Example, I have a pdf file on my phone, with my SNCF subscription (French railway company).
The pdf is 38.7 kb, the photo is more than 3.5 Mb (and bad quality).
I would like th join the pdf file to the associated barcode, because a train conductor checking my pass could ask me to show the real file instead of a picture, and if the pdf is attached to the barcode, I will find it very easily (without searching in the telephone).
Thank you

**Comment by TheLastProject** [comment]
You can already add image files as thumbnail, front or back image. Just click the option and choose "Select image from gallery". I'm not sure why people keep asking for this feature because it has existed for over a year already. If you can explain why this feature wasn't obvious to you, please add to #763.

PDF files aren't supported yet, I guess this issue is partially related to #496 (will share a lot of logic). May be more doable to add now you can long-play to open the image fully.

I'm not completely sure if PDF support is worth the costs it brings with it, especially security wise. See https://gitlab.com/fdroid/fdroiddata/-/issues/2672. It may be better to just use a third-party app to convert one PDF page into an image?

**Comment by guy-teube** [comment]
I don't know how to estimate the development and security costs of this feature.
I just know pdf is the default format original when cards are generated and sent to the users, when the card is dematerialized. By converting it into an image, there is
a loss of quality (especially if the document is long - should I convert in multiple images?), and no search is possible.
Sorry I did'nt see #496, my bad.
Probably my request in not related th Catima's development. I will look for the pdf in my files to show the controller.
