### ISSUE TITLE
Import from StoCard failed

### ISSUE THREAD

**Issue by Kachelkaiser** [CatimaLoyalty/Android#1242]
Hi,

i received my export from StoCard.

I doenloaded it. The first thing is that the filename does not contain the -sync. I renamed it an tried to import. I used the password provided

But the import fail with this failure:

protect.card_locker.FormatException

![grafik](https://user-images.githubusercontent.com/38027013/225414187-7dc2f80f-0586-4e8d-9c63-67b1f0aa5558.png)

What can I do?

**Comment by TheLastProject** [comment]
Can you send your Stocard export to me via email? I wonder if they changed the export format or something because that error is really weird.

**Comment by dakais** [comment]
Hi there! Same Issum! I received my dump today ind have the same error Massage.

thx 4 any support

**Comment by TheLastProject** [comment]
From the .zip file I got (sadly without password, so I could only see the structure) I could see Stocard completely changed their export format (quite frustrating, as they promised to fix their lack of GDPR compliance and keep me up to date and they clearly at very least haven't kept me up to date. If they fixed anything, we will see).

Please email me your export and password if you can so I can work on rewriting the importer for the new format.

**Comment by marcelser** [comment]
Same problem here. I have sent you my export including password. Hope this helps in debugging.

**Comment by TheLastProject** [comment]
Thank you for sending me exports @Kachelkaiser and @marcelser. The issue should be fixed through #1245. The change wasn't that big, mostly Stocard just moved all the json files from `foo.json` to `foo/content.json`. It seems neither of the exports had any photos attached so I couldn't ensure important that still works, but well, some things fixed is better than no things fixed.

I am, however, seeing some weird issue with the ITF barcode types being imported from Stocard with Catima saying that "The value is not valid for the selected barcode type", but that is most likely a different issue. It could be great if you could send me screenshots of those failing cards in Stocard and photos of the actual card so I can further debug that.

I'm going to double-check some other changes made since the last release and release a new version tomorrow most likely. Will take a few days to appear on F-Droid and Google Play Beta.

If you want to help test the changes already, I've attached a debug build to #1245.

**Comment by TheLastProject** [comment]
The update has been accepted by Google in the Open Testing program. I will start a gradual rollout to production soon as per the FAQ: https://catima.app/faq/

No word on F-Droid yet but I expect that to appear in the coming days too.
