### ISSUE TITLE
"Set barcode value" input field could use some padding

### ISSUE THREAD

**Issue by obfusk** [CatimaLoyalty/Android#1323]
![Screenshot_20230530-142950_Catima cleaned](https://github.com/CatimaLoyalty/Android/assets/1260687/c28bed7f-34ad-4570-82d9-11ac867315a3)

**Comment by TheLastProject** [comment]
It does bother me Android doesn't seem to have a default "textfield in dialog" class that will use correct padding, things will always look off, but I guess following the balance dialog here would be good.

**Comment by Swayam-Khare** [comment]
Hello! I would like to work on this issue. I noticed that the EditText is added programmatically to the dialog. So, I did some research on how I can add margin to it. Since it does not have any parent layout. Hence to set appropriate margin, I can first create a container view (probably a frame layout), add this EditText to the container, Set the margin and use setView method on the AlertDialog to put the container inside the Dialog.

I am still a beginner in Open-Source Contributions, so I don't know if I need to be assigned this issue or should I create a PR directly.

**Comment by obfusk** [comment]
@Swayam-Khare I'm not involved in maintaining Catima so I hope @TheLastProject will correct me if I'm wrong, but I would suggest reading the project's [`CONTRIBUTING.md`](https://github.com/CatimaLoyalty/Android/blob/main/CONTRIBUTING.md), which includes:

> Finally, you will need to submit your patches so that they can be reviewed and potentially merged into the main Catima repository. The preferred way to do this is to submit a Pull Request to the Catima project.

So I would assume you can simply create a PR for your suggested changes.

Thank you for working on this :)

**Comment by Swayam-Khare** [comment]
@obfusk I am gonna create a PR then. Thank you for your help 😃

**Comment by obfusk** [comment]
Fixed by #1328.
