### ISSUE TITLE
card name not displayed since 2.23.2

### ISSUE THREAD

**Issue by baudav** [CatimaLoyalty/Android#1344]
before 2.23.2 catima display below each thumbnail card the name.
Now, the name is not displayed, card with same thumbnail require to open to see the name.

**Comment by TheLastProject** [comment]
When redesigning I didn't really consider this a problem because it didn't seem likely. What's your use case for having multiple cards with the same thumbnail and why does setting a note not work?

My main idea is to replace the expand button in the top-right with a type of display button where people can choose exactly what fields to show below the card, with the following default:

- [ ] Name
- [X] Note
- [X] Balance
- [X] Validity

That should deal with your use case without looking ugly by default (because for most users it's duplicate data), although I'd still be curious what your use case is and why it isn't solved by notes or groups.

**Comment by baudav** [comment]
I use example Lidl and Lidl e-ticket, my children card with their name in card name for media library card, covid card first, second... The name define card and used to sort, not the note. Why use note when name exist. Note is used for url access, more detail, code...
Name is always fully displayed, when thumbnail card not always and no time to resize/crop/extend to add border for all card. Ex: intermarché, The film title for me,children 1,2.
If can choose option to display in expand it's good, and perhaps choose to display thumbnail or just name?

**Comment by TheLastProject** [comment]
> If can choose option to display in expand it's good, and perhaps choose to display thumbnail or just name?

It doesn't make much sense to me to display the name instead of the thumbnail, but maybe name display could grey out the thumbnail a bit and display text over it instead of below it like the note, so it'll still look good for custom thumbnails and use as little space as possible. Will need a moment to try that because Android UI is not my strength.

**Comment by baudav** [comment]
only to add an extra view.  I use the note to add url or email attached to card.  That's why I prefer to display the formatted name to correctly identify the card.  This is also the name that is displayed in the android home page by holding down.  I expressed my request badly, as I have names that allow my cards to be identified, I do not necessarily need to display the photo of the card, a condensed view with the name as in the android launcher would be good  to display more card on the screen.  Maybe to be able to define a customizable view per group?  Display of the name as the launcher in the display of all the cards, display of photo+name+note+point for the group of favorite purchases... There is also catima by leaving pressed power, it seems to me that it  is also the name that is displayed (but android version too old for me to use)
Sorry if my english is not very understandable

![IMG_20230604_073524](https://github.com/CatimaLoyalty/Android/assets/10183995/de47b1a8-24a2-49e3-b4a1-b1a4b9b9d5e5)
![IMG_20230604_073322](https://github.com/CatimaLoyalty/Android/assets/10183995/6eb0b801-7852-457c-a05f-1673e4c29541)

**Comment by TheLastProject** [comment]
Hi, I've been working on this a bit. Does this solve your use case?

[app-debug.zip](https://github.com/CatimaLoyalty/Android/files/11645259/app-debug.zip)

**Comment by baudav** [comment]
Hi, very fast...
the name is displayed on top of the photo, I expected to have it displayed clearly below.
difficult choice.. because the name is already displayed if I don't have a photo of the card.
![Uploading Screenshot_2023-06-04-12-06-21-172_me.hackerchick.catima.debug.jpg…]()

**Comment by TheLastProject** [comment]
So more like this?

[app-debug.zip](https://github.com/CatimaLoyalty/Android/files/11645655/app-debug.zip)

**Comment by baudav** [comment]
yes 👍, maybe reduce the font size a bit.

**Comment by TheLastProject** [comment]
Thanks for the report, helping me understand your use case and the testing. This will be in the next update. Will probably take about a week to give translators the time to translate a bit.
