### ISSUE TITLE
Pin field for gift cards

### ISSUE THREAD

**Issue by Cautious-Software701** [CatimaLoyalty/Android#1392]
Would be nice to have a pin field as I use Catima to store gift cards, which almost always have a pin. An alternative would be to create custom fields which users can configure themselves. Currently, I have to add this to the notes section. 

Would anyone else find this useful?

**Comment by TheLastProject** [comment]
How exactly does this PIN field or custom fields improve the app? You're talking about "having to put it in notes otherwise", but I don't see the problem with that?

I'll need more info on what a PIN field would add and how it would make the app better before considering this because right now it just sounds like additional complexity with no concrete benefit.

**Comment by TheLastProject** [comment]
> The PIN field could be shown under the barcode, and it could be hidden by default until you click on it.

That sounds like what the note field currently does: being hidden until tapped.

> Though you're right, it's not really a problem per se, but couldn't you say the same for the "Valid from" and "Expiry date" fields?

The plan is to send notifications when a card is about to expire (or becomes valid), see #410. I can't think of anything special that could be done with a PIN field.

So, thank you for your suggestion, but I think I will skip on implementing this feature. One of my goals with Catima is for the app to be very simple and the more things you add the more complex it becomes and I am personally not convinced the benefits of this feature are worth the added complexity.
