### ISSUE TITLE
Feature Request: Multiple Barcode Types (with different values for each)

### ISSUE THREAD

**Issue by antv199** [CatimaLoyalty/Android#1501]
I'm not sure if this was already mention or not, but I think it could be useful to have multiple barcode types for a card.

For example, a Funky Budha  membership card has both a bardcode and a QR code on the back of the card. Storing both of those would mean that if for some reason the QR code fails, the barcode can still be read. Kinda like a backup mechanism

Or a supermarket, which while they give you a physical barcode, digitally they also give you a QR code with a different identification serial number.

Currently, you can attach photos of the card alongside the barcode, but I think having the app generate the contents of the seperate format, like how it does with its primary method would save time.

**Comment by obfusk** [comment]
This would require database changes. Is this common enough that simply adding two cards is not a workable solution?

**Comment by TheLastProject** [comment]
I actually [tried implementing this in Loyalty Card Keychain long ago](https://github.com/brarcher/loyalty-card-locker/pull/337) but eventually dropped it because it conflicted with other features.

I think that using Groups to put these multiple cards together makes more sense, especially given how rare this is from my experience. Groups also allow you to switch between cards in there with the previous/next buttons in the bottom of the screen, so quick switching is supported too.
