### ISSUE TITLE
Actions with selected item / unification and simplification of manipulations with items & groups

### ISSUE THREAD

**Issue by osering** [CatimaLoyalty/Android#1585]
Hello.

There is option (by long pressing item) to select it and in upper row appears some options, like Edit and Copy icons. Edit is ok, but no use of Copy as nowhere afterwards there is possibility to paste copied item. There is no Move option (from one folder to another) as well.
Please implement move (paste would be great as well) option from one folder/group to another. Delete could be reasonable as well.
Move could be implemented as well with just dragging item to respective category.

P.S. Thanks for opensource card management app available in f-droid!

**Comment by TheLastProject** [comment]
The "Copy" option is actually "Copy ID to clipboard" (as it says when you long-press), so you copy just the IDs. But I understand this may be confusing because the icon is the regular copy icon.

Your suggestions for group management are a bit complicated, because a card can be in multiple groups and it's not clear to me what should happen if a card is in group A and B and you select it while in group B and move it to group C. Should it be in group A and C? Or only group C? Also with dragging, it isn't clear what exactly should happen in these more complex cases.

Is there any issue with the current batch group management system where you go to Groups -> Edit -> Select all the cards you want to be in that group? Is it just less discoverable?

**Comment by osering** [comment]
Thanks for prompt reaction!
Actually I don't see a point of one card being in multiple groups. And if it is, that it is with one UID and not a duplicate or triplicate.
What about "Copy ID" - there next to it is Edit icon - should it be Edit ID, in mind? And why regular user should know ID of group or item? How this info can be widely used?
The same could be attributed to Groups - if I long press on group name, I would also expect similar reaction - icon row or some bubble window with options - move, delete, rename, etc. (like in file managers), but nothing happens. It's pretty dead.
Or if way through some half hidden menu is considered better, then there should be menu item "Items/Cards"" next to Groups with similar functionality - to move, rename, delete, add. Then there would be consistency - one set of principles for both types of objects - Groups and Items/Cards. Otherwise it is also bit misleading that "+" on the main page is just attributed to Items (not Groups) and to do the same manipulation with groups one should act differently (in some sub menus).
I tried your suggestion through the "Groups -> Edit -> Select " and it did move. Frankly quite awkward and not intuitive way to do things. Why to invent wheel if the gold standard - Delete, Copy, Paste, Move, Rename - options would work like a charm and is much more conventional way for most of users. 
What is the reason for some item/card to be put outside of any sub-group? If somebody not sure what is the point of card? Also showing top group/folder "ALL" (which is all other sub-groups/folders inclusive) as the one of regular groups (in main page) seems hierarchy-wise incorrect as well as putting all cards (from folders of different level) together, without possibility to see to which group each belongs and without possibility to re-arrange them (they are arranged without any standard principle (name, creation time, modification time, owner, permissions) by default - rearranging groups has zero effect on this item order).
Actually - it would make more sense to look at "All" as a filter, not a sort of supergroup but misleadingly put in one level with its subgroups. So instead of that there could be some "General/Generic/Default" group, which is easily renamed.
If you make association comparing this to regular file system, there is root (/), there is folders in root. there can be files in root as well as folders, but you never (almost)  put all files from root and its subfolders in one mess-list. There is always shown subordination, like:
/supercard1.card
/banking_cards/card1.card
/banking_cards/card2.card
/id_cards/card1.card
/shopping_cards/card2.card
It can be displayed as as files tree.
On most conventional operating/file system (Linux, BSD, Solaris, Windoze, Android / ext4, fat32, ntfs) you create, rename, delete, move files and folder more or less (depends - GUI or CLI) same way (here I am referring to present order in Catima: special submenu and interface for folders/groups, but very different arrangement for files/cards). Structure is done in complicated way, not with KISS principle in mind.
Sorry for not being short...

**Comment by TheLastProject** [comment]
You're not putting a lot of different requests, completely different from your initial request, in a single message. You also haven't answered my questions. But I'll do my best to answer anyway.

> Actually I don't see a point of one card being in multiple groups. And if it is, that it is with one UID and not a duplicate or triplicate.

I have a few generic groups like "Card" (for all store cards), "Ticket" (for event tickets), "Coupon" (for coupons). If I go to some event which gives me both tickets and coupons, I can temporarily make a second group for that event to keep my old organization while also having everything for that event together. How others use it, I can't know, I can't track, but removing multi-group support for a single card would break some of my workflows.

>  What about "Copy ID" - there next to it is Edit icon - should it be Edit ID, in mind? And why regular user should know ID of group or item? How this info can be widely used?

This was requested in #10 to copy the card ID and added back in the Loyalty Card Keychain days (2017) by the previous developer. I just never had a reason to remove the copy ID option, but it may indeed not be useful and this ticket shows it's potentially confusing. Maybe it should be removed.

>  The same could be attributed to Groups - if I long press on group name, I would also expect similar reaction - icon row or some bubble window with options - move, delete, rename, etc. (like in file managers), but nothing happens. It's pretty dead.

The ability to long-press a group in the top bar in the main view and get a few options like "Move left", "Move right", "Manage cards", "Rename" and "Delete" seems like a logical addition to me. Feel free to make a new issue for that.

> Or if way through some half hidden menu is considered better, then there should be menu item "Items/Cards"" next to Groups with similar functionality - to move, rename, delete, add. Then there would be consistency - one set of principles for both types of objects - Groups and Items/Cards.

I disagree. Catima is about managing cards, a card is the main thing to interact with. Groups are a secondary convenience feature. Cards and groups should not be treated the same as cards are more important.

> Otherwise it is also bit misleading that "+" on the main page is just attributed to Items (not Groups) and to do the same manipulation with groups one should act differently (in some sub menus).

Android design guidelines state that the Floating Action Button should be for the primary action, in this case, adding a new card and this is what most apps do. Keeping similar behaviour to other apps and following official guidelines that have had user acceptance testing is a good practice and not one I plan on moving away from.

> I tried your suggestion through the "Groups -> Edit -> Select " and it did move. Frankly quite awkward and not intuitive way to do things. Why to invent wheel if the gold standard - Delete, Copy, Paste, Move, Rename - options would work like a charm and is much more conventional way for most of users.

Because, as I stated, a card can be in multiple groups. We can't change that now without breaking stuff for users. And thus, this flow you propose can't work because it is not clear what should happen in case the card is in multiple groups already.

> What is the reason for some item/card to be put outside of any sub-group?

There is no such thing as a "sub-group" in Catima. There is only one level of group. A card is in 0 or more groups. There is no hierarchy. See it more as "tags".

"All" is indeed not a group, it just shows you all cards regardless of which group. It therefore allows you to quickly filter: "I want to see all cards, I only want to see cards in group X, I only want to see cards in group Y, etc."

> It can be displayed as as files tree.

A file tree is something every nerd like us understands, but many non-technical users do not understand it, and thus it makes the UI more confusing for them. A file tree also takes longer to browse, the more levels you add the longer it takes to get to the item you need. It adds new questions (should the content of subdirectories be shown? If so, how?). It adds complexity and slows down one of the most important tasks: finding the card you're looking for.

> Structure is done in complicated way, not with KISS principle in mind.

Just because it's not your style doesn't mean it's not KISS. I've talked with quite a few people before implementing this and had quite some testers. People have often talked about how much they like how groups work in Catima and how simple they find it. It works really well for the vast majority of users and hits the sweet spot for flexibility needed while not being overwhelming for the vast majority of users.

--------

Summarizing, I think you're right that long-pressing one of the groups on the top of the screen in the Catima home screen should probably do something and I'd welcome a new ticket for that. And the "Copy ID" option is probably confusing and given how little people will use the feature maybe it should be removed to reduce risk of confusion. The rest, well, I disagree they are improvements :)
