### ISSUE TITLE
Add ability to swipe between card barcodes

### ISSUE THREAD

**Issue by d4f5409d** [CatimaLoyalty/Android#1609]

**Comment by TheLastProject** [comment]
Can you give a bit more details on:
1. Which things you want to swipe between exactly? "card barcodes" is a bit vague to me because a card only has one barcode, do you mean swiping between cards or between barcode/front image/back image on a single card? For the last you can already long-press the barcode/image to switch.
2. What's your use case? Why don't the current options work for you?

**Comment by d4f5409d** [comment]
![Screenshot_2023-10-28-10-03-31-52_0e0fb5e4c7b0c70cd406dc034ad65059.jpg](https://github.com/CatimaLoyalty/Android/assets/76624594/40114131-4705-473c-b6e6-d7ae1b9ac896)

**Comment by d4f5409d** [comment]
What
