### ISSUE TITLE
Missing option to auto-rotate screen on barcode display regardless of OS settings

### ISSUE THREAD

**Issue by Self-Perfection** [CatimaLoyalty/Android#1671]
Autorotating screen on barcode display is the default behavior of LoyaltyCardKeychain and I miss it.

In my opinion this is the most convenient way to display the barcode.

Related to #1660 as it is mostly useful for "no barcode" records.

**Comment by TheLastProject** [comment]
Would be a new setting under Settings -> Barcode orientation then.

Would need some testing but I believe this is `ActivityInfo.SCREEN_ORIENTATION_SENSOR`, which is described on https://developer.android.com/reference/android/R.attr#screenOrientation as

> Orientation is determined by a physical orientation sensor: the display will rotate based on how the user moves the device. Ignores user's setting to turn off sensor-based rotation.

Which sounds like it best matches this request because the default setting ("Follow system") does respect the system settings.

As for name, not sure, something like "Always rotate (ignore system settings)"?

**Comment by TheLastProject** [comment]
This was already fixed in #1689. And forced landscape mode has been supported for years already.
