### ISSUE TITLE
Support thumbnail from already added photos

### ISSUE THREAD

**Issue by skwde** [CatimaLoyalty/Android#1675]
Currently there are only the options

- Select color
- Take a photo
- Select image from gallery

It would be nice if one could choose the thumbnail from already added photos of the front / back of the card.

A workaround is to take just 2 pics of the front card, but supposedly this also means that they are stored twice.

**Comment by TheLastProject** [comment]
I think this feature could make sense. Preferably, adding 2 options to the list, only visible if a front or back image are set:

- Use front image
- Use back image

We could then load the current front/back image into the image cropper so changes can be made to crop it as desired for the thumbnail. Saving it as a new image would be best imho, sure, it's slightly more storage, but it keeps the code much simpler and more maintainable which is very important, especially for a small project with little developers like this.

The next questions become:
1. Should it be possible to use the current thumbnail as front or back image? Perhaps not, as it is most likely cropped to too small a size.
2. Is it clear enough to users what the current front and back images are? Most likely not, as the "Photos" tab just shows 2 images. This UI should probably be redesigned to display the images next to each other if there is enough space with "Front image" and "Back image" shown above the images to make it clearer to users.

I'm labeling this as low priority because in most cases users will already have the image they want to use stored in their gallery, so this would be a minor time save for most. But it does feel sensible to support and could be supported with relatively little and simple code I believe.

**Comment by MozarM** [comment]
The approach sounds reasonable and user-friendly. Adding options to use the front or back image as the thumbnail directly from the existing photos can indeed simplify the process and improve user experience. 

Addressing the questions:
1. It might be best not to allow using the current thumbnail as the front or back image since it's likely cropped to a small size and may not provide the desired clarity.
2. Redesigning the UI to display the front and back images next to each other with clear labels can enhance user understanding and interaction.

Considering it as a low priority makes sense, but it's still a valuable enhancement that could save time for users. Overall, this approach seems practical and feasible.

**Comment by petRUShka** [comment]
Actually, I originally came here to post about the same issue. It's good to know it's already here. So, I'll just add a comment to an existing one.

Having this feature significantly boosts the process of adding a bunch of cards at once (in my case, more than 50). Currently, I have to take new photos three times: twice for the front (as a front and as a logo) and once for the back. It would be very nice to have the ability to set a front photo and then choose it as the main image for a card.

**Comment by TheLastProject** [comment]
I've implemented this in #1934. I think this code will work fine (it seems to work fine on testing). However, I feel the current amount of changes has gotten big enough and this requires new translations so I'm planning to first do a new Catima release before I merge this in, to give translators some more time to translate. So this sadly won't make it into the next release. However, it should be in the release after that. No ETA, but seeing my general release tandum it would probably be in about a month :)
