### ISSUE TITLE
Space card numbers

### ISSUE THREAD

**Issue by pikrzysztof** [CatimaLoyalty/Android#1679]
I'd like the app to not display long card numbers in one continuous sequence and group digits in threes or fours instead.

Example: 

This is the current way of presenting card digits

![image](https://github.com/CatimaLoyalty/Android/assets/3964215/fee6844f-a297-48fc-8704-19596f5bde79)

what I'd like to see instead:

![spaces](https://github.com/CatimaLoyalty/Android/assets/3964215/f480d55b-1602-4974-9a11-69fdceb55f88)

**Comment by TheLastProject** [comment]
I don't think Catima should make assumptions on the correct way to display card values especially because it may affect the receiving end (if I get a coupon with code "12345678" and I enter it as "1234 5678" on the store's website, the coupon may be refused).

As I see it, manually changing the Card ID value to make it contain a space is a decent enough workaround for those who want the code to be displayed in a prettier way regardless of validity.

**Comment by pikrzysztof** [comment]
> I don't think Catima should make assumptions on the correct way to display card values especially because it may affect the receiving end (if I get a coupon with code "12345678" and I enter it as "1234 5678" on the store's website, the coupon may be refused).

That's a fair point. But we still can do better for readability. We can use colours:

![image](https://github.com/CatimaLoyalty/Android/assets/3964215/d861df06-3267-44d1-9c3a-c77d4900038b)

or underlining:

![image](https://github.com/CatimaLoyalty/Android/assets/3964215/cd50e638-ae28-4af5-bba3-7da08931708a)
