### ISSUE TITLE
Using dominant colour instead of edge colour as background can look out of place

### ISSUE THREAD

**Issue by Progress1** [CatimaLoyalty/Android#1753]
I manually select image to card. I crop it on black background (see image 1)
![Screenshot_2024-01-25-23-33-01-482_me hackerchick catima_1](https://github.com/CatimaLoyalty/Android/assets/10151485/8483e979-bfd3-4718-a24c-79a95232766e)
But when app render card images it display on sides lines that should't be there (see image 2). Correct behavior is pure black background.
![Screenshot_2024-01-25-23-33-16-322_me hackerchick catima-edit](https://github.com/CatimaLoyalty/Android/assets/10151485/4b8042ca-5fb4-424c-a7da-2bad4411231f)

**Comment by TheLastProject** [comment]
That looks like it is the code that extracts the dominant colour and adds it as a background layer to make images that don't truly fit look better. I agree the behaviour in this specific case is... suboptimal. I'll have to think of how to best solve this.

**Comment by TheLastProject** [comment]
I may have some time to look at this soon, could you please update some of the images it goes wrong with? Preferably inside a .zip file just to be sure no compression could possibly affect the testing?

**Comment by TheLastProject** [comment]
Looking at it more thoroughly, I think these images are actually *not* the correct size.

Catima uses [the same dimension as physical banking cards](https://en.wikipedia.org/wiki/ISO/IEC_7810#ID-1). So, 85.60 by 53.98 millimetres (see also https://github.com/CatimaLoyalty/Android/blob/6937342226b56ef9104aab5df7a749f70f99d246/app/src/main/res/layout/loyalty_card_view_layout.xml#LL55C3-L55C3 for the code)

Your images are all slightly off in different ways:
1day.jpg: 527 by 332 pixels (should've been 526.48 by 332 pixels)
billa.jpg: 525 by 327 pixels (should've been 518.58 by 327 pixels)
deca.jpg: 524 by 332 pixels (should've been 526.48 by 332 pixels)

Testing this more, I can't reproduce it myself. This is what I'm getting with those same images: ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/5143a05f-b5c0-4708-8999-a27720166e30)

The easiest way to make it work is to just crop the image on the coloured background, so not on the black border. It looks good on the main screen (although the background colour fill isn't applied on the card view, I've added it there for consistency in #1762).

![image](https://github.com/CatimaLoyalty/Android/assets/1885159/ac0cd704-4b90-4c2e-8e44-dd5ea8162068)
![image](https://github.com/CatimaLoyalty/Android/assets/1885159/b395a040-1fdb-461b-aad9-b8f8f2edeb37)
![image](https://github.com/CatimaLoyalty/Android/assets/1885159/ba42d9ba-8c37-464e-b844-4e1f10b2c171)

One of the 2 fixes you suggested already exists:
> User can cut with any ratio: then you take "closest side", stretch with original ratio to fit display space and center, gap on sides is filled with background. Don't add "intelligent" background with dominant colour -> just add pure background color (or maybe some setting to keep both functionality if it's really needed)

You can already move the cropper however you want and it stretches while keeping the aspect ratio and fills with a background. However, I don't think using a pure static background colour is a good idea as it is more likely to look out of place than the dominant colour. I'm also not really interested in adding a setting for something so minor, having too many settings creates applications where users will have to first fiddle with the settings for an hour before they have something usable, Catima should make good decisions out of the box.

It may be worth looking into using the "border" colour instead of the dominant colour, that would have prevented the extra green added around the black in your case. It is confusing I can't reproduce this though, but I do see room for improvement there.
