### ISSUE TITLE
Swiping from card to card

### ISSUE THREAD

**Issue by saturnfreeway** [CatimaLoyalty/Android#1772]
Hi - thanks for a great app. One question/ idea: might it be possible to implement a swipe feature that enables swiping from card to card? In this case I use two cards in one shop, and this would greatly enhance the experience.

**Comment by TheLastProject** [comment]
I'm not opposed to the idea of swiping but Catima used to have swiping between groups on the main screen and I got a lot of complaints of it responding too quickly and a lot of complaints about it not being responsive enough.

I also worry swiping between cards may be confusing to people because:
1. If you add a photo to a card, it's already displayed together with the barcode with an arrow to the right, so people may expect swiping to swap between barcode and photos
2. It's easy to accidentally for (especially non-technical) users to accidentally touch the screen while trying to move Catima in front of a scanner and swipe support would increase the chance of accidental swapping.

Would #1553 also solve your use case, perhaps?

**Comment by saturnfreeway** [comment]
Can see that swiping can cause issues elsewhere. Navigating with volume buttons would definitely be an improvement., the small previous and next buttons are a bit of a hassle when you're trying to be quick at checkout. Thanks for taking it into consideration.

**Comment by Korb** [comment]
I agree that the archaic way of scrolling using buttons is a bit annoying. I suggest using gestures at the top of the screen to scroll through cards, where the name of the card and its thumbnail are displayed. At the very least, this can be done as a duplicate feature that can be disabled in the application settings.

**Comment by TheLastProject** [comment]
I'm going to consider this fixed given #1553 is fixed. If it doesn't work well enough we can look back into it with a good why.

**Comment by Korb** [comment]
@TheLastProject, the mentioned changes will be available in version 2.31.2?

**Comment by TheLastProject** [comment]
I'm not sure what version number the next release will be getting yet but yeah, unless something really critical comes up everything merged into the main branch will generally be added to the next release. You could already build a debug APK from the main release if you want to test early :)
