### ISSUE TITLE
User confusion with thousand separator in balance parsing

### ISSUE THREAD

**Issue by neutric** [CatimaLoyalty/Android#1775]
My phone is set to "country/region" Germany with "language" English.

When editing a card, adding/editing a €-balance is done as "x,xx", just as is common for Germany. 

The quick spend feature displays the balance as "€x.xx" with a period instead of a comma, though. If you then enter the amount spent as "x.xx", so with a period, the amount subtracted is €xxx, because the period is not the correct decimal point character and thus ignored.

**Comment by TheLastProject** [comment]
I sadly can't reproduce this, even when I choose "Germany (English)" it consistently uses `,` in both places can you show your exact Android language settings and maybe add some screenshots?

**Comment by thewholelifetolearn** [comment]
I encounter the same issue with Catima v.2.29.0 in French. I wanted to update a card with 10€ balance with a 4.65€ expense. Catima then showed 0,00€. I then tried receiving 4.65€, and Catima showed 475,00€.
Forcing Catima to English did the trick: spending 4.65€, I still have 5.35€ on it.
There seem to be an issue on managing locale numbers.

**Comment by TheLastProject** [comment]
As stated before, I can't reproduce it and need more info. I'm not sure what info I will need to reproduce but a screenshot of Android's locale settings (like I asked the original reporter) so I can make sure I have the exact same combination of locales might be a start. Knowing your Android version is probably good too, maybe this only happens on specific Android versions.

**Comment by TheLastProject** [comment]
Actually, you seem to be reporting something different. It would be correct that using `.` would deduct more because the decimal separator in French is `,`: https://www.smartick.com/blog/other-contents/curiosities/decimal-separators/

4,32 = 4 Euros and 32 cents
4.32 = 4 (thousand separator) 32 = 4320 Euro

So this is expected behavior with how Java parses currency numbers and not a bug. I don't disagree it can be confusing to the more techy crowd who is used to always use the American decimal separators as used in programming instead of their own country's though.

**Comment by TheLastProject** [comment]
Unless you see Catima show you `.` instead of `,`, which shouldn't be happening in the French locale. In which case I need more info like I asked the original reporter. Screenshots of the issue, Android locale settings and the Android OS version would be a good start.

**Comment by thewholelifetolearn** [comment]
Here are screenshots from the app and android settings. I hope it will help you to understand the issue better.
![Screenshot_20240509_134634_Catima](https://github.com/CatimaLoyalty/Android/assets/823564/ebbd6ad0-238d-445a-82ef-0ce28d1cf753)
![Screenshot_20240509_134744_Settings](https://github.com/CatimaLoyalty/Android/assets/823564/bf85d6bb-edc4-4601-a48d-6801572ac846)

**Comment by thewholelifetolearn** [comment]
The language settings: 
![Screenshot_20240509_152051_Settings](https://github.com/CatimaLoyalty/Android/assets/823564/d2748dab-1b64-45d7-8d7f-67a43fadccbb)

**Comment by TheLastProject** [comment]
That's technically correct behaviour. Catima displays "20,00" (with a comma) correctly. And you're entering "5.85" (with a dot) but dot is the "thousand separator" in French. So Java's parsing parses that as "5 (thousand separator) 85" and turns that into "5850". This is as expected, but not super user-friendly.

However, technically correct is not always the same as logical. Given most users will be unlikely to actively use thousand separators it sounds like it most likely will improve the UX if the "thousand separator" is just automatically translated to a decimal separator (so both "5.85" and "5,85" would deduct 5 Euro and 85 cents). I'm not sure what the original user ran into, perhaps it's the same thing but I didn't understand it.

Anyway, I'm going to mark this as a bug, even though it isn't really, because it's just confusing to people :)

Suggested code change: In the parseBalance function in Utils, replace the thousand separator with the locale's decimal separator before running NumberFormat's `.parse` function. And te

**Comment by thewholelifetolearn** [comment]
I do understand the technical aspects but as you can see on one of the screenshot, the comma "," is inactive. I don't have the possibility to use it. So I can't mark a decimal in the French way. As such, I consider it as a bug. If I had the choice to use comma "," and dot ".", I would understand that it is just an UX design. Maybe, there is an option to force the locale keyboard?

**Comment by TheLastProject** [comment]
Oh, I didn't notice that. That's quite weird. Sounds like a keyboard bug to me (maybe Samsung keyboard?) but yeah, that would make it unusable in your case.
