### ISSUE TITLE
Display loyalty cards as a text list, without thumbnails

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#1806]
I suggest adding the ability for the user to display a list of cards on the main screen of the application as a text list. Maybe even two columns. Perhaps broken down by blocks based on the first letter of the name.

The fact is that with a sufficiently large number of cards (more than a hundred), the user essentially always uses the search. That is, the appearance of the cards is not important to him in the case when the choice comes from a pair of options that are displayed after entering the first two or three characters of the name. Because, standing in front of the cash register, it’s hard to scroll through dozens of screens looking for the card you need. A text list is much faster in this situation.

**Comment by TheLastProject** [comment]
I have had people request a list view before but I am not interested in adding this to Catima. Implementing and maintaining two different UIs costs a lot of time (which I don't really have), increases complexity and thus the risk of bugs and increases the chance of user confusion (users may accidentally switch, sounds stupid, but things like that happen all the time).

[Catima 2.9.0](https://github.com/CatimaLoyalty/Android/releases/tag/v2.9.0) had a list view ([see screenshot](https://github.com/CatimaLoyalty/Android/blob/v2.9.0/fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-01.png)) but it was replaced with the current view to have larger, easier touch areas and make cards more easy to tell apart by using a larger font and colours/images. If you really want a list view you could always downgrade to that version :)

I am wondering though, and I mean this with no disrespect, but what is the exact issue? Typing 2 or 3 characters into search seems like a pretty fast and good default workflow. You could also use groups, favourites or other sorting methods to have your most commonly used cards on top. I only have a bit over 10 cards myself so I'm having a hard time understanding the experience of a 100+ card user as I've never been in that situation myself.

Would implementing something like fastScroll help? It would put a scrollbar next to the main screen to easily let you scroll about halfway or whatever you would need:
![fastScroll example gif](https://github.com/CatimaLoyalty/Android/assets/1885159/a04c19f2-470e-46ae-8393-e79c5f3b3f66)
(Image source: https://medium.com/android-news/fast-scrolling-with-recyclerview-2b89d4574688)

**Comment by Korb** [comment]
I think an example would be **bookmarks in a browser**. If there are two or three dozen of them, you can place them on the start page of the browser, and select the one you need when creating a new tab. They will be presented with a picture, and this will be quite convenient. But if there are significantly more tabs, the stream of thumbnails is no longer suitable for comfortable use. And it is more appropriate to use text output (menu or sidebar).

Another example: the view of **files in the file manager**. Despite the advantage of previewing the first page of documents in thumbnails, I much more often have to use the list (or table) view.

Third: media player. If it has a mode for displaying **album covers** on tracks and albums, this is convenient when you have a small media library, but absolutely inconvenient when it grows.

Be that as it may, I heard you, and thank you for your reasoned refusal. I hope that version 2.9.0 will not have any problems with compatibility with Android 14, nor with import / export to the current versions of your application, which my family members will probably use.

**Comment by TheLastProject** [comment]
Yeah, I totally see how the current UI could be slow to get through with many cards. Although big touch zones would simplify quickly stopping at an entry, they also mean there's less data on the screen and take longer to scan. It's a tough problem to solve, the kind of situation where I wish I had a professional UI designer in my life :sweat_smile: 

I think I'll experiment with fastScroll at least, that might be a quick win if you have stuff sorted alphabetically and have a rough idea of what letter you want to go to to get to that letter, so that's at least a start. If you have any other suggestions to improve the usability with a high amount of cards without changing too much of the current UI I'd love to hear them.

Catima 2.9.0 should probably run fine on Android 14, it was targeting targetSdk 31 (Android 12) which isn't that far off. I don't think I changed the backup format between 2.9.0 and now so an export from now should most likely still import fine. Of course, make sure to disable in-app updaters if you use something like IzzyOnDroid :)

**Comment by Korb** [comment]
Let me give you another reason why a list in some situations would be more convenient than mosaics/tiles. Take a look at two screenshots:
![Screenshot_2024_0628_162429](https://github.com/CatimaLoyalty/Android/assets/3509797/dbfbdd53-668b-4b63-9f18-9e04ea6d9b82)
![Screenshot_2024_0628_162407](https://github.com/CatimaLoyalty/Android/assets/3509797/e5e527bc-d831-4dc0-b93c-36e9f7c3d751)
The search results seem to show identical cards. However, it is not. Some of the names are cut off, making it impossible to understand how they differ (without opening the card pages). At the same time, the tiles do not even display an ellipsis, which would suggest that the name is not displayed in full. The fact is that I live in a country in which the only official language is based on the Cyrillic alphabet. At the same time, the concept of foreign in business is very often associated with prestigious, which is why business owners promote English-language names of their brands. At the same time, legislation forces them to use only Cyrillic names in official documents. Since the app can only be searched by the Name field, I have to duplicate names in both alphabets, which prevents the qualifying information from fitting within the tile boundaries.

**Comment by TheLastProject** [comment]
> Some of the names are cut off

That should never happen, the text should automatically scale based on the content and always fit. If names get cut off that's a bug, please create a new issue for that with one or more names that happens to so I can try to fix that.

> Since the app can only be searched by the Name field, I have to duplicate names in both alphabets, which prevents the qualifying information from fitting within the tile boundaries.

As written in another issue (which you couldn't possibly have read at the moment of me replying here), the note field is searched as well. But the real issue here seems to be the title is cut off, that should simply never be happening.

**Comment by Korb** [comment]
> If names get cut off that's a bug, please create a new issue for that with one or more names that happens to so I can try to fix that.

Done — #1961
