### ISSUE TITLE
Google Play: "Can't install Catima (2.29.0)"

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#1850]
Installed version: 2.**28**.0
Target version: 2.**29**.0 (Google Play)
Download size: 3.01 MB
Required OS: Android 5.0 and up

> Can't install Catima - Loyalty Card Wallet
> Try again, and if it still doesn't work, see common ways to fix the problem
> Send feedback / Understood

OS version: Funtouch OS 14
Model: V2153
Hardware version: MP_0.1
Build number: PD2201OF_EX_A_14.2.7.2.W20
Baseband version: S.HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.71
Kernel version: 4.19.157-perf+, 1 Fri Mar 1 16:22:31 CST 2024
Compile time: 1 Mar 2024 11:02:07
Android security update: 1 March 2024
Google Play system update: 1 March 2024

**Comment by TheLastProject** [comment]
Hmm, I asked some people to try to update their Catima on Google Play today and they had no issues. I can also see several thousand users already updated without issue. So I think you're probably running into a temporary Google Play issue. Maybe try again and see if it works later and otherwise use Google's debugging steps.

Also make sure you're not trying to update a non-Google Play install through Google Play as that won't work.

So I'm closing this as I don't think there's anything I can do here, it seems to be a Google Play issue you're running into.

**Comment by Korb** [comment]
You are right, for some reason the Google Play application displayed the Catima application as installed from Google Play, although it was installed using F-Droid. In addition, in the system properties of the installed application it was written:

> App details: App installed from F-Droid

I have not noticed Google Play behaving like this before. Could this be due to the fact that my beta tester status is displayed on Google Play?

> Catima - Loyalty Card Wallet (Beta)
> You're a beta tester for this app. Future updates will include beta versions.
> Private feedback to developer
> Only the developer can see this feedback
> You're a beta tester
> You'll see new features before the public does. Give your feedback to the developers to help them improve. You can leave the beta test at any time. Certain data on your use of the app will be collected and shared with the developer to help improve the app.
> Leave

**Comment by TheLastProject** [comment]
Well, glad we found the cause :)

I've definitely seen Google Play try to update apps from F-Droid before and back when I was still part of F-Droid I tried to get that treated as a high priority issue (sadly to no avail).

Being a beta tester would definitely cause this to happen more often because Google Play Open Testing tends to approve the update several days before F-Droid builds it, so there is more time between the update being on Google Play and the update being on F-Droid.

I believe Google Play allows you to disable updates per-app so that it probably the easiest workaround. This issue itself is sadly out of my control.

**Comment by Korb** [comment]
> I've definitely seen Google Play try to update apps from F-Droid before and back when I was still part of F-Droid I tried to get that treated as a high priority issue (sadly to no avail).

Is it possible/advisable to make different identifiers for the two stores? That is, ultimately, to make it so that Google Play does not see the application installed via F-Droid and does not waste traffic, battery charge and does not irritate the user with notifications that the update installation was not successful, but will be repeated later. Because even if you disable automatic updates for an application, the user only needs to go to the "Manage apps and device" section, find several updates there that for some reason were not installed automatically, and click "Update All" so that the Google Play application downloads and tries to install all updates, including those for which automatic updates are disabled.

**Comment by TheLastProject** [comment]
Changing the app ID means breaking updates for all existing users. If this was a brand new app, it would be sensible. But given we've been like this for 5 years it would mean breaking updates for tens of thousands of users with no way to tell them (and even if we couldn't not everyone is technical enough to migrate everything to a new install).
