### ISSUE TITLE
FR: Share text to app instead of image

### ISSUE THREAD

**Issue by StevenAlexander44** [CatimaLoyalty/Android#1860]
If I get a new code as text, it would be nice to either have an option to share that text to the app directly (maybe you can also add a default option for barcode type in settings?), or at least have a one-click option to add a new card from clipboard (next to the + button on the main page). As it currently stands, I need to do 7 steps from pressing the "+" to be able to add from my clipboard.

I can provide further explanation if needed.

**Comment by TheLastProject** [comment]
My first feeling here is to reject this request because I've learned through the year that one of the most prevalent cases of people thinking Catima is broken is caused by people entering a barcode manually (which is also why there is now a dialog window explicitly warning you that it's better to scan). Adding a setting to have a default barcode type for shared text also seems like asking for trouble to me, as it increases the chance of users accidentally creating cards they can't use (because the barcode type is wrong) even further.

I think it's good to take a step back: what's your exact use case? You're talking about receiving text you want to store. Is this theoretical as a "this has never happened but I think it would be nice if I could" or is this something that commonly happens? How often does this happen in a way where you're not also given an image as well? What kind of workflow would this feature improve?

**Comment by StevenAlexander44** [comment]
I don't *need* to show a qr, but it's faster to use the qr than to type out the 7-8 character code on their slow touchscreens (it does happen to be a fast food joint). The "No barcode" option would be great!
