### ISSUE TITLE
Transparent thumbnails are unreadable

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#1972]
After adding [this file](https://drive.google.com/file/d/1rRDK387R4lgKG3BZkvQ5rOVTcMGi3kdL/view?usp=drive_link) as a thumbnail (option `Select an image from gallery`):

![Screenshot_20240704_092855](https://github.com/CatimaLoyalty/Android/assets/3509797/7c3b2192-b771-4e40-836d-253a5204c902)

Instead of a text inscription on some background, the following is displayed:

![Screenshot_20240704_092907](https://github.com/CatimaLoyalty/Android/assets/3509797/a14dee82-d0fd-4771-94a4-5cceb55799ea)
_(screenshot edited to reduce image height, barcode blurred)_

View of the loaded image in the graphic editor:
![2024-07-04_20-56-36](https://github.com/CatimaLoyalty/Android/assets/3509797/85ffece3-4a85-4912-9443-86930855c5d4)

That is, the color of the inscription filled the entire image, making it monochromatic.

## Expected Behavior

1. disable loading images with transparency, or
2. allow the user to select a background color for each such image, or
3. After loading the image for the thumbnail, you should always combine this image (top layer) and the solid gray color in the area `#4A4A4A`..`#4C4C4C` (bottom layer).
4. After uploading the image for the thumbnail, always overlay it on a gray wallpaper with a mosaic of the Catima logo =)

**Comment by TheLastProject** [comment]
Okay, so, this makes me wonder if anyone EVER used the transparency support.

But doing 1 is risky because it might break existing setups (this is the one case where I did with I had some kind of telemetry so I could know if removing this support would break anyone's setup, especially because jpeg would likely be smaller for most images (#891))

Given the background colour for images has more often caused issues (see #1753) it might also be worth considering disabling that altogether (or using some static "transparent-like" colour, a light white or dark grey)

**Comment by HenkDemper** [comment]
I made all my cards with logo's because it looks nicer & can be accessed quicker than text.

Transparency support proves useful, would not remove that. Sometimes the chosen background color does make the image unreadable/look bad though as pointed out above.

Likewise when you have for example a square image (with/without transparency), the added bars left/right or top/bottom with auto-chosen color might look good or not. Sometimes you would like to extend the colors at the edge.

In both transparency & extend cases to have a color picker option for the background (default could be proposed color) would make it perfect.

**Comment by Korb** [comment]
> In both transparency & extend cases to have a color picker option for the background (default could be proposed color) would make it perfect.

I'm guessing the next FR will be **a color picker**, — not just a color wheel with a separate brightness scale (or circle and circumference as shown below), but an eyedropper that allows you to pick colors from a photo/scan of card.

![photo_2024-11-11_16-16-37](https://github.com/user-attachments/assets/33028e47-92ec-482e-9b81-c1eb84b6c1df)

**Comment by TheLastProject** [comment]
Perhaps a good way that will be future-proof for improved detection (by assuming the correction was correct but allowing the user to override it) would be to, after selecting an image, still automatically choosing the colour but to show a dialog window with the generated image with background colour after finishing the cropping activity and ask "Does this look right?" and allow the user to choose "Yes" or "Change background colour" (or, if it turns out to be easy and user-friendly enough (would need some testing), maybe just show the image with the colour and allow changing it in the dialog window itself).

**Comment by HenkDemper** [comment]
Sounds like a good plan. Bedankt Sylvia 👍🏻

**Comment by mingyee2** [comment]
If it’s possible to do, you might consider simply not having a background colour for such images, so that it takes the background of the app itself (white or black)
