### ISSUE TITLE
Custom global full screen barcode display height does not save its value

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#1975]
## Reproduction sequence

1. Add two cards with barcodes to the application.
2. Open the first card and click on the barcode. (The barcode will be displayed in full screen.)
3. Use the slider at the bottom to change its height to, for example, 20% of the screen height.
4. Close full-screen viewing by clicking on the checkmark in the middle of the bottom of the screen.
5. By clicking on the button in the lower corner of the screen, go to the second card and click on the barcode. Make sure that its height in full-screen viewing mode does not match the one that was set in the third point.

**Comment by TheLastProject** [comment]
This is by design. It's not a "global display height", it's a per-card display height.

The reason it's designed like this is because in the vast majority of situations, displaying the barcode as big as possible allows for the easiest and quickest scanning. However, some stores may use scanners that have very limited space in which case putting that store's barcode on the top of the screen and resizing it to a size that fits will help.

It's quite rare, but I've ran into it once or twice that the scanner was really designed for very small plastic cards and I had to push my phone against the wall and resize the barcode to be smaller just for that one store.
