### ISSUE TITLE
Keep the screen on during export

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#1978]
In the case of large collections of cards, exporting can take quite a lot of time, much more than the time of automatically turning off the screen, automatically locking the device and unloading some applications from memory. As a result, the zip archive for export will not be saved completely, and the user will not even receive a notification about it.

## Workaround

In the system settings "Background power consumption management (Changing how an app uses your battery can affect its performance)" set the Catima to "Unrestricted (Allow battery usage in background without restrictions. May use more battery)".

Upd. And on during import — same problem.

**Comment by TheLastProject** [comment]
The real problem is #513 and that is what needs to be fixed. But that is quite complex. Given I already implemented #1715 as a workaround while the import/export is in this broken state means it makes sense to add more workarounds for current brokenness as long as #513 is broken but I'm not a huge fan of spending so much time on bandaid solutions instead of the real solution :(
