### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by aspx1981** [CatimaLoyalty/Android#2198]
Dear Developer Team,
I really like this app idea and I think add IOS support would be great.
Is there anything preventing that ?
Thanks

**Comment by TheLastProject** [comment]
Catima is written using Java and Android XML. It's sadly not cross platform. So iOS support means writing a second app.

I would love to have iOS support, but I don't have the time to write 2 apps and I don't have Apple hardware or an Apple developer account.

If someone else is willing to write an iOS version I'd welcome it with open arms :)

Closing this because even though I'm interested it's not something I have the time to do (and it's not related to Android).

**Comment by aspx1981** [comment]
thanks for your answer, I'd like to help but unfortunately I don't have the knowledge.
I think this app and server should be very similar to Passbolt CE, just instead of storing/showing passwords and share them, do it with barcode and QR code.

**Comment by kintaro1981** [comment]
how about writing on the webpage and in github that you are open to welcome ios developers?
