### ISSUE TITLE
shortcut to change balance

### ISSUE THREAD

**Issue by HK7679** [CatimaLoyalty/Android#2240]
I love that you can add the function of points and balance to a bar code to keep record of the remaining balance.

I have some membership cards where I buy like 10 entries to the gym in advance. Currently, I have to click the shopping cart symbol, enter 1 and click pay. It would be a nice feature to add the option of a shortcut to change the remaining points by a certain defined amount. In addition to the shopping cart symbol there could be symbols '-' and '+' that subtract or add the defined number of points or Euros or Dollars... from the balance. It would be one click instead of a bunch of clicks and numbers.

**Comment by TheLastProject** [comment]
I understand this request but I'm not sure if it's worth it? We're talking about 3 taps currently: tap cart, press 1 (keyboard already popped up automatically), tap spend.

I do understand we could add extra quick buttons for common options, but I think that would be slower due to the added "mental load" of more options on the screen (and who decides what is "common"?).

A long-press on the cart icon would be possible as shortcut too, but that could cause issues for people with motor issues.

So I think for this issue I'm going to prioritize code and UI simplicity over saving 1 or 2 taps, sorry :)
