### ISSUE TITLE
[Feature request] Add the possibility to archive cards

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#644]
I would love to be able to hide some old cards by archiving them!

**Comment by TheLastProject** [comment]
It makes sense to be able to archive instead of delete.

The most sensible implementation would probably to add a new database field to each card named "archived" and to filter it out of every single group. If there are any archived cards, a new "group" (not a real group, just like "All" is not a real group) will be shown in the main screen named "Archived", always at the last position in the list of groups.

Then there is the question of archiving or unarchiving.

I think the best way to keep the UI clean would be to add the following:
1. On edit screen, "archive" button next to "delete" button to archive (or "unarchive" button if currently archived).
2. On long-press in main screen, "archive" or "unarchive" button (both if some selected cards are archived and some aren't? should never happen though but still, for logic)

**Comment by Altonss** [comment]
> I think the best way to keep the UI clean would be to add the following:
> 
>     1. On edit screen, "archive" button next to "delete" button to archive (or "unarchive" button if currently archived).
> 
>     2. On long-press in main screen, "archive" or "unarchive" button (both if some selected cards are archived and some aren't? should never happen though but still, for logic)

Both ways could be implemented I think, as both seem to logical on UI/UX point of view :)
What could be done when long-pressing in main screen, is to select multiple cards and archive all the selected :)

**Comment by bahadirkaratas** [comment]
Hi @TheLastProject,

I would like try working on this, could you assign it to me?

**Comment by TheLastProject** [comment]
Go ahead @bahadirkaratas :)

**Comment by bahadirkaratas** [comment]
I cannot run the project and getting the following error:
General error during conversion: Unsupported class file major version 61

What might be causing that? I would appreciate any kind of help.

**Comment by TheLastProject** [comment]
Looks like you may be using a wrong Java version in Android Studio: https://stackoverflow.com/a/67101848. That's just a guess though, first result on a web search, because I never had such an issue before.

**Comment by bahadirkaratas** [comment]
Thanks for answering so quickly. I was thinking the same thing but I just wanted to ask if it was a specific issue about the project. I will continue searching for solutions :)

**Comment by Jasielprogramador** [comment]
Hello, sorry for bothering, but I'm having a lot of issues finding where the "All" group is filled with all the cards, could you help me a little pls

**Comment by TheLastProject** [comment]
In MainActivity.java, all the tabs get made. Each of these tabs has a "tag" set with the group reference in the database, except for the "All" tab, which purposefully has `null` set to it is clear it is not in the database:

https://github.com/CatimaLoyalty/Android/blob/98c9c9ce151086694aa7c9cedeb7cb8b119a376a/app/src/main/java/protect/card_locker/MainActivity.java#L438-L441

Then, when a tab is selected, the tag is read and set to the `mGroup` (currently displayed group) variable:

https://github.com/CatimaLoyalty/Android/blob/98c9c9ce151086694aa7c9cedeb7cb8b119a376a/app/src/main/java/protect/card_locker/MainActivity.java#L189-L196

That group is then used in the DBHelper class to get the correct list of entries:

https://github.com/CatimaLoyalty/Android/blob/98c9c9ce151086694aa7c9cedeb7cb8b119a376a/app/src/main/java/protect/card_locker/MainActivity.java#L384

(In the case of "All", the group is `null` and `getLoyaltyCardCursor` doesn't filter anything)

Now that I'm thinking about this more, creating a new "Archived" tab may actually not be the best solution, because then it becomes hard to see which group an archived card belonged to. Instead, I think it might be easiest to add a new argument to that called `showArchived`, put some checkbox or something somewhere (overflow menu? sort menu?) to show or hide archived. Can put some archived icon on archived cards somewhere (where the star is for starred entries maybe?). I'm open to suggestions though!

**Comment by Jasielprogramador** [comment]
Ok, i could add a filter in the sort menu, i think that would be the best, also i could add the star thing but i have to think  about how to do it . Thanks for taking time for helping me :)
