### ISSUE TITLE
The padlock setting (for a card) is not being remembered

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#719]
When locking the card (the rotation if I understood it correctly) then view the qr-code/barcode in fullscreen and the go back to the card view, the lock isn't enabled anymore.

System information:

Android 5.0.1
Device: Samsung Galaxy Core Prime

**Comment by pree-T** [comment]
Is this issue still open? May I work on it? Can someone help me as I am new to open source contribution?

**Comment by TheLastProject** [comment]
This issue is still open, yeah.

Take a look at https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/ for a guide on developing with git. Only step 1 through 6 are important right now, the steps after are more for if you want to keep contributing after your first change was accepted :)

Hope the guide helps and don't worry about making mistakes, I will review the pull request and help you out if necessary.

I don't know if you have done Android development before, but if you haven't you will probably want to download Android Studio to make your changes in.
