### ISSUE TITLE
Mobile Linux version

### ISSUE THREAD

**Issue by kj7rrv** [CatimaLoyalty/Android#740]
Hello,
I have a PinePhone, a smartphone that runs Linux. If I wrote a Linux app with similar features, would it be okay to support sharing with catima.app links and use the Catima name and logo?

**Comment by TheLastProject** [comment]
Hey @kj7rrv!

Supporting catima.app URLs is always okay, the Android app is designed to respond gracefully to both valid and invalid URLs. If it ever doesn't, bug reports are very welcome! The format is documented here: https://github.com/TheLastProject/Catima/wiki/Card-sharing-URL-format. Even if you end up not using the Catima name and logo, you are always welcome to generate catima.app URLs and import from them!

For using the Catima name and logo, that would be possible under some conditions because I want to make sure that any version of Catima meets some expectations:
1. Your app does not use any proprietary code, we are an open source project after all :)
2. It supports importing and exporting a [Catima export .zip](https://github.com/TheLastProject/Catima/wiki/Export-format) so that users can easily switch between platforms and their data is never "held hostage" even accidentally.
3. The development would happen under a "Catima" organisation on GitHub (I will move this project and the website there then) so I do have some control if stuff would start going wrong and we can keep it organized (just to be able to protect the name and quality, but I expect and want to be able to pretty much stay hands-off and leave the Linux project to you)
4. We will keep tracking feature parity between the Linux and Android client and try to keep it at a reasonable parity (most importantly, being able to both show the same barcode types). I understand that you're doing this as a hobby too, so I'm not going to threaten deadlines or anything ridiculous like that, just want to make sure we try our best to not break compatibility between each other.

Of course, all of those requirements can't be ready in a day, but it would be the minimum to start publishing it on the catima.app website. It would be completely okay for you to release versions which don't have all these features yet, just call them "alpha releases" so it's clear that it's not expected to be able to do everything.

If that sounds good to you I will happily create the GitHub organisation and give you a repository there. I will also create a repo to track feature parity (probably just a table). If the app reaches a quality that I think is good enough I'll happily also put it on the catima.app website. And I will buy myself a PinePhone to check out your project because it sounds pretty cool :)

Sorry for the huge wall of text, but to summarize: if you are willing to work together with me to make sure Catima Android and Catima Linux work well together I would love to have a Linux project that uses the same name and icon :)

**Comment by kj7rrv** [comment]
Okay, sounds great! I would have followed all of those anyway.

**Comment by kj7rrv** [comment]
Okay, sounds great! I would have followed all of those anyway. (Sorry if this double posted)

Do you want me to try to keep the UI similar, or should it look like a native app?

**Comment by kj7rrv** [comment]
I'm probably going to write the Linux version in Python if that's okay with you. Would you mind creating two repos, `catima.py` and `catima-gui`? `catima.py` would be a library for handling Catima files and links, and `catima-gui` would be the actual GUI.

**Comment by TheLastProject** [comment]
>Do you want me to try to keep the UI similar, or should it look like a native app?

I'd say just go native, it is probably what people would expect on the platform.

>I'm probably going to write the Linux version in Python if that's okay with you. Would you mind creating two repos, catima.py and catima-gui? catima.py would be a library for handling Catima files and links, and catima-gui would be the actual GUI.

That sounds okay. I want to finish what I'm doing first, so feel free to make your own repos and we'll just move them over later so you don't have to wait for me :)

**Comment by kj7rrv** [comment]
Okay, no problem. I'll try to get the library started later today.

**Comment by kj7rrv** [comment]
Is the `ITF` `barcodetype` the same as [ITF-14](https://github.com/bwipp/postscriptbarcode/wiki/ITF-14)?

**Comment by kj7rrv** [comment]
Oh it looks like it's [Interleaved 2 of 5](https://github.com/bwipp/postscriptbarcode/wiki/Interleaved-2-of-5)

**Comment by kj7rrv** [comment]
I just want to make sure I'm reading https://github.com/CatimaLoyalty/Android/wiki/Card-sharing-URL-format correctly. If `barcodetype` is not set, there is no barcode; if `barcodetype` is set but `barcodeid` is not set or is empty, the barcode is the same as the card ID; and if `barcodetype` and `barcodeid` are set, the barcode has its own ID, right?

**Comment by TheLastProject** [comment]
All the barcodetypes use the names ZXING uses for them. It is most likely the least effort for you if you also use ZXING.

> If barcodetype is not set, there is no barcode; if barcodetype is set but barcodeid is not set or is empty, the barcode is the same as the card ID; and if barcodetype and barcodeid are set, the barcode has its own ID, right?

100% correct yes

**Comment by TheLastProject** [comment]
@kj7rrv I've given you the power to create new repositories under CatimaLoyalty, so go ahead and make your repository there.

The Android client is now in a repo named "Android" because it is for Android only. Feel free to create repos as you see fit (I'm not quite sure how broad your version will target. Like, if it'll only be Linux on phones, only a certain Linux phone distro, Linux-only, cross-platform, etc.)

**Comment by kj7rrv** [comment]
It's written in Python, so the library should work anywhere python works. The GUI will be GTK-based, so it should work on any Linux distro but look best on Gnome-based DEs.

It looks like ZXING, or at least the available python bindings, doesn't support generating barcodes (only scanning them), so I'm using treepoem, which uses BWIPP internally. It looks like the Web share UI also uses BWIPP; I found a map from Catima to BWIPP barcode type names there that I'm using in the library. I'll probably use ZXING for scanning.

**Comment by kj7rrv** [comment]
Right now the library (still on my local computer) supports decoding and encoding catima.app URLs to a Python object. There are a couple fields it doesn't handle yet (expiry and headercolor). Expiry should be easy; I just haven't done it yet. Headercolor will be a little bit more complicated because it will have to convert Android colors to a format Python can use.

**Comment by kj7rrv** [comment]
I created the library repo: https://github.com/CatimaLoyalty/catima.py
