### ISSUE TITLE
Rotation lock improvements

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#771]
This would simplify the UI. Do really a lot of people use the rotation feature? Maybe it would make more sense to hide the option in the parameter (by setting it to on by default).
What do you think about it? It would also hide the lock button on the card, which I didn't understood when I first saw it. I thought it was a button to lock the edition of the card, to protect it from unintentional changes.

**Comment by TheLastProject** [comment]
Okay, so, this feature is actually a bit more complex than it seems because rotation changed on Android through time. When OS-level rotation is enabled, old Android versions will instantly rotate. Newer versions however will show a small icon in the bottom-right corner to tap. The whole point of being able to lock rotation is mostly to help users on older Android versions, as on newer versions you can't accidentally rotate the device without confirming. See https://source.android.com/devices/tech/display/rotate-suggestions for more details.

Given this behavioural change, the option actually behaves differently between old Android and 9+ Android.

| Android version | Rotation unlocked | Rotation locked |
| - | - | - |
| 5 - 8 | Rotates immediately | Doesn't rotate |
| 9+ | Show rotation icon in navigation bar | Doesn't rotate |

So, having put that out of the way, I do have a very different opinion from you on this whole issue.

Given the following:
1. I believe likely more people use this rotation feature than use the share and starring feature (assumption: no tracking means no data to confirm this).
2. We have more than enough space in the card view screen.
3. This feature is only useful for users on Android devices before version 9.

I think I would actually prefer the following:
1. Always show the rotation lock icon, but have the default change based on what's in settings.
2. Change the icon to be more obvious (so, [screen rotation](https://fonts.google.com/icons?selected=Material+Icons+Outlined:screen_rotation:) and [screen lock rotation](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Ascreen_lock_rotation%3A)).
3. Hide the rotation option in settings and icon in card view on Android 9 and up completely (and ignore the user saved setting).

These are kinda multiple different tasks, but all 3 of these tasks seem like good first issues. I know this is very different from what you suggested, but it does hide the icon on the Android versions where it's useless, so you still get the "simplified UI" without removing the feature for those who may use it.

**Comment by go2null** [comment]
> on newer versions you can't accidentally rotate the device without confirming.
I have Pixel 6 with Android 12 and it rotates automatically. :(

I agree with @Altonss, I would be just happy with it never rotating, or at least in the Settings. 

BTW, until I read this, I just ignored the lock icon as I too thought it was about looking the editing function.

**Comment by TheLastProject** [comment]
I don't know what I was doing when I did my original research, but your post made me re-check stuff and I updated my previous post.

I still disagree with @Altonss about hiding the rotation feature completely, but I think the correct fix is different from what I documented earlier.
