### ISSUE TITLE
Brightening Barcode failing on Android 11

### ISSUE THREAD

**Issue by gsmitheidw** [CatimaLoyalty/Android#824]
Since my phone has upgraded from 10 to 11 (Nokia 7.2} the brightening function is no longer working when I chose any loyalty cards.

The same issue affects older Loyalty Card Keychain too so I assume this isn't just a coincidence bug.

**Comment by TheLastProject** [comment]
I have never seen anything like this before and I have been using Android 11 for many many months on my main device.

Just to verify:
Settings -> Brighten barcode view is on?

What Catima version? And how do you open a card? Start Catima -> Click card?

What was the brightness level before opening the card? Did it change at all? If so, to what?

**Comment by gsmitheidw** [comment]
I'm on version 2.15.2 and yes I have the brighten setting enabled in Catima's settings.

I've tried a variety of cards, none brighten. I've screen brightness set to manual on my phone, but that shouldn't matter. I have tried changing theme from system (dark) to light but that doesn't make a difference. 

All cards were imported from Loyalty Card Keychain except one new one I added yesterday, but all behave the same. 

My exact model of Nokia 7.2 is TA-1196 and build 00WW_3_490

**Comment by TheLastProject** [comment]
That's extremely odd. I wonder if Nokia broke something, because this feature has not been changed in Catima in very very long and I've had people on all types of Android versions report it working fine. It's definitely not a general Android 11 issue because otherwise I would have it too (I run LineageOS on my Fairphone 3 which is very very close to stock Android 11).

The code changing the screen brightness is also not deprecated: https://developer.android.com/reference/android/view/WindowManager.LayoutParams#screenBrightness

https://github.com/CatimaLoyalty/Android/blob/6d134009beb03d2143fbee76402a325d62414364/app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java#L460-L462

I really think this is a device-specific issue and not a Catima issue unless you can find an app that does manage to work correctly on your device (in which case, if it is open source, it may be worth looking into what they do, although I still am hesitant to touch this code because it has been in production for years and this is the first report of an issue I get). Because of that I am going to close this issue, but feel free to reopen if you happen to find reasons to believe my idea is wrong.
