### ISSUE TITLE
[Settings][UI]: allow changing toolbar position

### ISSUE THREAD

**Issue by PetbkA** [CatimaLoyalty/Android#898]
Modern smartphones are usually "tablet-sized", so you have to stretch your finger to reach e.g. search button.

It would be nice to have an option in Settings that would allow to move toolbar to the bottom

**Comment by TheLastProject** [comment]
I get your issue and while it seems bottom bars are allowed nowadays in [Material Design 3](https://m3.material.io/components/bottom-app-bar/overview), I'm not sure about this.

In developing Catima, I keep a few guiding principles, mostly to keep the code maintainable and simple to me:
1. Stay as close to the official Android design guidelines as possible (Google has UX designers and huge teams to test what works best and is easiest to understand for most people, I don't)
2. Limit the amount of settings (whenever there's a setting, there's 2 code paths instead of 1 which means increased maintenance burden and chances of bugs)

While it seems okay to just move everything to the bottom bar then, I'd like the user interface to be consistent everywhere and I'm not sure what to do about the card view activity yet.

**Comment by TheLastProject** [comment]
This has pretty much become impossible due to the work done for #925, so I'm going to close this. Sorry, UI/UX is really hard.
