### ISSUE TITLE
[Settings][UI]: add "App screen orientation" option

### ISSUE THREAD

**Issue by PetbkA** [CatimaLoyalty/Android#899]
Currently only _Lock barcode orientation_ option is available, and it's working pretty strange - when enabled, barcode screen will be forced to a _portrait_ orientation, and opening the app in landscape mode and then going to some card will rotate screen to a portrait.

IMHO it would be better to have fixed orientation across the app, so adding _App screen orientation_ option would be nice

**Comment by TheLastProject** [comment]
Related to #771.

I think it may be really good to replace "Lock barcode orientation" with a new option called "Barcode orientation" with 3 options:
1. Follow device (default)
2. Landscape
3. Portrait

I guess this might be the missing link for #771 :)

**Comment by PetbkA** [comment]
> replace "Lock barcode orientation" with a new option called "Barcode orientation"

I don't see a point of having one part of the app in locked orientation and the other in auto

**Comment by TheLastProject** [comment]
Well, if you just want the app to be a certain orientation it makes much more sense to me to use the global Android setting (which is most likely more reachable).

This is mostly a convenience feature to help people who unintentionally trigger device rotation when trying to show their barcode to a scanner.

What is your exact use case for which app-wide would work better?

**Comment by PetbkA** [comment]
> makes much more sense to me to use the global Android setting (which is most likely more reachable)

Catima is the only app I want to always be in portrait orientation. This one is better when I'm holding bags in one arm and want to show the barcode to cashier. I don't know why, but there were cases when I accidentally turned it to landscape.

In other apps auto orientation is better. For instance,  when I'm watching YouTube, I'm searching the video in portrait mode and opening it in fullscreen by rotating to landscape.

If I would use locked orientation forced by the OS, it would affect all apps, so I had to turn it on before launching Catima/going to grocery store and turning it off upon return. Not very comfortable.

I also tried to search for some app that would force orientation for certain apps but found nothing, that's why I've created this issue

**Comment by TheLastProject** [comment]
> Catima is the only app I want to always be in portrait orientation. This one is better when I'm holding bags in one arm and want to show the barcode to cashier. I don't know why, but there were cases when I accidentally turned it to landscape.

Always? Also when editing cards, managing groups, changing settings, etc? Because you're talking about showing the barcode to a cashier, in which case locking only the view activity would be sufficient?

> In other apps auto orientation is better. For instance, when I'm watching YouTube, I'm searching the video in portrait mode and opening it in fullscreen by rotating to landscape.

That sounds like what would be perfect for you is if the YouTube app would have an option to force landscape when viewing videos, like how I currently implemented locking the barcode view to a chosen orientation in #901.

> I also tried to search for some app that would force orientation for certain apps but found nothing, that's why I've created this issue

I found [Auto Auto-Rotate](https://gitlab.com/juanitobananas/auto-auto-rotate) and [Rotation Manager](https://github.com/AleixDev/AppSpecificOrientation_FOSS/) on F-Droid (linking to the source code as they link to both Google Play and F-Droid), maybe those will work for you? (Haven't tested them though)

---

I don't know, the main reason I'm trying it with only the view activity is because it's closest to the old rotation locking method. Given Catima is currently on a 4.770 star average on Google Play I like to think people like the app the way it is so I am trying to make changes as minimal as possible.

I don't know, making choices is difficult and no matter what I choose someone will be unhappy always, just have to try my best to think of all possible use cases :sweat_smile:

**Comment by PetbkA** [comment]
> Always? Also when editing cards, managing groups, changing settings, etc?

No, I'm using only the main screen, barcode screen and card editor (to change color, label, type of the barcode and it's value).

> in which case locking only the view activity would be sufficient?

May be it would but sometimes I accidentally turned the main screen to landscape. May be it was 'cause I tried to reach _Search_ button or the latest used card (which is at the top left corner). Don't remember exactly.

> That sounds like what would be perfect for you is if the YouTube app would have an option to force landscape when viewing videos

No, 'cause sometimes I turn the phone back to potrait to see comments while viewing the video. Also if landscape would be forced when playing videos, returning to search would require:
1. A tap to show navbar (it's being hidden in fullscreen);
2. Tap on _Back_ button to return from fullscreen to video page;
in addition to rotating phone back to portrait. 3 actions instead of 1 isn't better.

> I found [Auto Auto-Rotate](https://gitlab.com/juanitobananas/auto-auto-rotate) and [Rotation Manager](https://github.com/AleixDev/AppSpecificOrientation_FOSS/) on F-Droid

Thank your for suggestion. However, both of these are working as a persistent service, and the first uses "all but selected in _fixed_ orientation" while I would prefer "all but selected in _auto_". The second was updated in 2014 the last time so I didn't event tried it, considering it works as separate service too.

I see you've closed the issue. Eventually your app is still the best so I'm OK even without this feature 🙂
