### ISSUE TITLE
Feature Request: Swipe through cards.

### ISSUE THREAD

**Issue by laberlaib** [CatimaLoyalty/Android#925]
Hi Catimateam,

is it possible to implement a Swipe-Feature to flip through cards of one group?
Me and my familiy, we use barcodes at the check-in of a sports facility. So I created a group with a card for each of us and it would be very handy if I were able to switch between us four instead of pressing back and than choosing the next person.

As the app of my local supermarket refues to run on rooted phones, this app becomes even more useful, so keep up the good work!

laberlaib

**Comment by TheLastProject** [comment]
I get your feature request and it makes sense. Right now, swiping on a card is already implemented if the card has a barcode, front and back image to quickly switch between those. I understand the usefulness of this feature, but I'm not sure how to implement it in a way that makes it clear for users the option exists and prevents people from accidentally triggering it. If you have suggestions of how to make this clear in the UI that would be great.

**Comment by TheLastProject** [comment]
> I do not understand what happens when you click the arrow on the footer (marked with a ? on my image), I just end up with a collapsed card without any information (second image). This space could be used and it could be accessible either by an arrow or by swiping up-and-down.

I find this quite an interesting note and it happens fairly often that people don't know what this button does (it shows the notes, expiry and other details of a card) and I've had multiple people who wanted to maximize the card get confused because they both have an up arrow, so redesigning and reusing this space does make some sense.

I wonder if it would be sensible to replace this with a Material Design 3 [Bottom app bar](https://m3.material.io/components/bottom-app-bar/overview). I could keep the edit icon in the same space and put 3 icons in there: Info (which shows the details currently shown when pressing up), Previous (go to previous card in group) and Next (go to next card in group). So, simple arrows as you suggested in your mock-up, but without using extra space.

![image](https://user-images.githubusercontent.com/1885159/176890490-88197965-568c-4f98-b0aa-cd76fd8c188a.png)

**Comment by Bruno-FGM** [comment]
If I may, you can swipe in 4 directions... 2 are used at present. Leaves 2 possibles. 
Something like swipe right and left to switch between info of the card, and up and down for switching between cards. 
Or could be the other way round..

**Comment by TheLastProject** [comment]
Up and down is already used as well, for making the barcode fullscreen or regular sized again.

Anyway, the bottom bar implementation is almost done. Just need to find some time to clean stuff up. PR #937 should already build for those curious to try.

**Comment by Bruno-FGM** [comment]
Did not realized up & down was already used... my bad

**Comment by TheLastProject** [comment]
I still have to fix some spotBugs things but here's a debug build of the new layout with this feature:

[app-debug.zip](https://github.com/CatimaLoyalty/Android/files/9126221/app-debug.zip)

Wonder what y'all think :)

**Comment by laberlaib** [comment]
As it became clear, I do not use all the features so I can just say export from stable an import in the above version worked well.
As well as all the other stuff I tried.
![20220717_093249](https://user-images.githubusercontent.com/81492190/179388724-449259c3-25a6-46f9-b17c-2ba2faae618f.jpg)

Concerning the newly designed bottom line (imho!):
1. I got a 6,3 inch phone and I still think, that the arrows are a little small.
2. The positioning of the arrows should be the same on both sides so that you can find them without looking - all-outer-left and all-outer right, so the (i) must me moved somewhere else.

**Comment by Altonss** [comment]
Another issue I encountered (having a really small screen and Android 5) is that the card id is not readable. I also noticed it before this change, but just wanted to point it out as it does not seem "correct".
![image](https://user-images.githubusercontent.com/66519591/179389249-733e4594-c402-4ac6-ac97-2bf08a916edc.png)

**Comment by TheLastProject** [comment]
> I got a 6,3 inch phone and I still think, that the arrows are a little small.

Hmm, the sizing seems consistent with the guidelines to me: https://material.io/components/app-bars-bottom#specs. Especially because I haven't gone out of my way to change them from the defaults. They also seem similar to the icons in the top bar to me.

> The positioning of the arrows should be the same on both sides so that you can find them without looking - all-outer-left and all-outer right, so the (i) must me moved somewhere else.

Hmm, I do agree it does feel a bit off, but I think the info icon placement makes sense. It contains your notes, expiry, the balance, etc. All kind of info that should be very easily reachable. Maybe one of the top icons can be put on the bottom line but I'm not sure which.

Share: too uncommonly used to have such an easily reachable position
Favourite: feels weird to have a toggle together with icons which aren't toggles
Duplicate: Starts a whole new screen and too uncommon
Archive: Uncommon and a toggle
Delete: Very destructive

I guess "Favourite" is the least wrong to put in the bottom, but I'm still not sure. I'll try I guess.

> Another issue I encountered (having a really small screen and Android 5) is that the card id is not readable. I also noticed it before this change, but just wanted to point it out as it does not seem "correct".

Did this change make it worse? Otherwise it should probably be a new issue.

---

I find it most worrying how inconsistently placed the maximize button is on both your screens now, that definitely needs fixing :(

**Comment by laberlaib** [comment]
> Hmm, I do agree it does feel a bit off, but I think the info icon placement makes sense. It contains your notes, expiry, the balance, etc. All kind of info that should be very easily reachable. Maybe one of the top icons can be put on the bottom line but I'm not sure which.

Or you just change the order?
![20220717_093249small](https://user-images.githubusercontent.com/81492190/179395339-70ad370e-a643-4407-9edc-06db7a909e3b.jpg)

Size does not matter to much, if there is a guideline, i am a strong supporter of standards

**Comment by TheLastProject** [comment]
> Or you just change the order?

I originally put them in the very corners, but I was annoyed at the buttons jumping in the old setup. But I realize now that I could just have the list wrap around on the start or end of list (previous button on first item: go to last item, next button on last item: go to first item), would've been way better.

So I'll start doing that, yeah, thanks for pointing it out again.

I also realize that there are some RTL bugs that will need fixing first.
